version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # Disable Warning "mbind: Operation not permitted"
    volumes:
      - db:/var/lib/mysql
  adminer:
    image: adminer:4
    container_name: adminer_container
    restart: always
    ports:
      - 8081:8080
  server:
    image: server
    container_name: server_container
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-db:3306/school?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "password",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
		"spring.h2.console.enabled" : "false"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - springmysql-net
    depends_on:
      - mysql-db
volumes:
  db:
networks:
  springmysql-net:
