version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # Disable Warning "mbind: Operation not permitted"
    volumes:
      - db:/var/lib/mysql
    networks:
      - springmysql-net
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8081:8080
  server:
    image: server
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/school?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - springmysql-net
    depends_on:
      - mysql-db
volumes:
  db:
networks:
  springmysql-net:
